### ISSUE TITLE
tvl adaptor statuses checklist

### ISSUE THREAD

**Issue by bencao** [opentvl/opentvl#15]
Ethereum Top TVL Projects

- [ ] Maker (returned 1.43b expect 9.97b)
- [x] AAVE (returned 8.61b expect 8.66b)
- [x] Compound (returned 8.86b expect 8.86b)
- [ ] Uniswap (returned 2.47b expect 6.71b)
- [ ] Curve (adapter broken w/ opentvl)
- [ ] Sushi (returned 1.7b expect 4.40b)
- [ ] InstaDApp (adapter broken w/ opentvl)
- [x] Liquity (returned 3.2b expect 3.21b)
- [ ] Yearn (returned 2.15b expect 3.19b)
- [x] Balancer (returned 2.48b  expect 2.40b)
- [ ] Synthetix (adapter broken w/ opentvl)
- [ ] Bancor (returned 86k expect 1.8b)
- [ ] Polygon (returned 2.55b expect 1.46b)
- [x] Vesper (returned 1.34b expect 1.27b)
- [x] Flexa (returned 1.23b expect 1.26b)
- [x] mStable (returned 57m expect 58.7m)
- [x] 88mph (returned 41m expect 44.5m)
- [ ] bZx (returned 9.9m expect 28.7m)
- [x] Fortube (returned 6.6m expect 6.0m)

Binance Smart Chain

- [ ] Pancakeswap (returned 7.8b expect 9.6b)
- [ ] Venus (backlog)
- [ ] Pancake Bunny (backlog)
- [ ] Ellipsis (backlog)
- [ ] MDEX (implementing)
- [ ] Belt Finance (backlog)
- [ ] Autofarm (backlog)
- [ ] Alpaca Finance (backlog)
- [ ] Nerve (backlog)
- [ ] Beefy.Finance (backlog)
- [ ] BTCST (backlog)
- [ ] Fortube (implementing)
- [ ] Goosefinance (implementing)
- [ ] Bakeryswap (returned 149m expect 176.6m)
- [ ] Acryptos (returned 359m expect 413m)
- [ ] Safemoon (returned expect)

Huobi Eco Chain

- [ ] MDEX (implementing)

**Comment by yueqiaocertik** [comment]
# Fortube

```
Cannot find price for contract 0x1fcdce58959f536621d76f5b7ffb955baa5a672f in chain eth
Cannot find price for contract 0x04abeda201850ac0124161f037efd70c74ddc74c in chain eth
Cannot find price for contract 0xba50933c268f567bdc86e1ac131be072c6b0b71a in chain eth
Cannot find price for contract 0x9afb950948c2370975fb91a441f36fdc02737cd4 in chain eth
Cannot find price for contract 0x59d4ccc94a9c4c3d3b4ba2aa343a9bdf95145dd1 in chain eth
Cannot find price for contract 0x9be89d2a4cd102d8fecc6bf9da793be995c22541 in chain eth
Cannot find price for contract 0x8064d9ae6cdf087b1bcd5bdf3531bd5d8c537a68 in chain eth
Cannot find price for contract 0x4c17f7abdbf507f7f18113faf01fd78c94d60090 in chain eth
```

Problems for Fortube are that the chainlink price oracle does not have price information for certain token contracts. We may still need to fallback to coingecko, or we may use other price oracle services?

**Comment by yueqiaocertik** [comment]
# AcryptoS

## Problems

There are still some tokens do not have prices, for example, ```SWINGBY```. This token is not available on coingecko, but you can trade on pancakeswap:

![image](https://user-images.githubusercontent.com/78632306/116774682-1c402b00-aa13-11eb-906a-7440790a7813.png)

Maybe we can use the same price oracle used by pancakeswap?

### Tokens missing prices

```json
{
    "0xb8C540d00dd0Bf76ea12E4B4B95eFC90804f924E": {
        "source": "https://bscscan.com/token/0xb8c540d00dd0bf76ea12e4b4b95efc90804f924e",
        "symbol": "QUSD",
        "decimals": "18",
         "price": 0,
         "amount": "296752558655534627557464",
         "usdAmount": 0
    },
    "0xfCe146bF3146100cfe5dB4129cf6C82b0eF4Ad8c": {
         "source": "https://bscscan.com/token/0xfce146bf3146100cfe5db4129cf6c82b0ef4ad8c",
         "symbol": "renBTC",
         "decimals": "8",
         "price": 0,
         "amount": "911447490",
         "usdAmount": 0
    },
        "0xeD28A457A5A76596ac48d87C0f577020F6Ea1c4C": {
        "source": "https://bscscan.com/token/0xed28a457a5a76596ac48d87c0f577020f6ea1c4c",
        "symbol": "pBTC",
        "decimals": "18",
        "price": 0,
        "amount": "25007611745216739642.30475122314688704893",
        "usdAmount": 0
    },
    "0x71DE20e0C4616E7fcBfDD3f875d568492cBE4739": {
        "source": "https://bscscan.com/token/0x71de20e0c4616e7fcbfdd3f875d568492cbe4739",
        "symbol": "SWINGBY",
        "decimals": "18",
        "price": 0,
        "amount": "866623307058855620265547.08973490778000073446",
        "usdAmount": 0
    },
    "0xAC51066d7bEC65Dc4589368da368b212745d63E8": {
        "source": "https://bscscan.com/token/0xac51066d7bec65dc4589368da368b212745d63e8",
        "symbol": "ALICE",
        "decimals": "6",
        "price": 0,
        "amount": "5142093096.55776288455940294944",
        "usdAmount": 0
    },
    "0x947950BcC74888a40Ffa2593C5798F11Fc9124C4": {
        "source": "https://bscscan.com/token/0x947950bcc74888a40ffa2593c5798f11fc9124c4",
        "symbol": "SUSHI",
        "decimals": "18",
        "price": 0,
        "amount": "16965637421050063575379.1862091711608028398",
        "usdAmount": 0
    },
}
```

## Full results

```json
{
    "USD": 395274926.0346986,
    "SUMMARY": {
        "bsc": {
            "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56": {
                "source": "https://bscscan.com/tokens",
                "symbol": "BUSD",
                "decimals": "18",
                "price": 1.0002,
                "amount": "12918600668728425663297915.20471470778985125303",
                "usdAmount": 12921184.388862172
            },
            "0x55d398326f99059fF775485246999027B3197955": {
                "source": "https://bscscan.com/tokens",
                "symbol": "BUSD-T",
                "decimals": "18",
                "price": 1.0002,
                "amount": "6966923734034562355737751.36447731594953327078",
                "usdAmount": 6968317.118781369
            },
            "0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3": {
                "source": "https://bscscan.com/tokens",
                "symbol": "DAI",
                "decimals": "18",
                "price": 1.001,
                "amount": "3093415580552715323400205",
                "usdAmount": 3096508.996133268
            },
            "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d": {
                "source": "https://bscscan.com/tokens",
                "symbol": "USDC",
                "decimals": "18",
                "price": 1.0002,
                "amount": "11513982656785424254873985",
                "usdAmount": 11516285.453316782
            },
            "0x4BD17003473389A42DAF6a0a729f6Fdb328BbBd7": {
                "source": "https://bscscan.com/tokens",
                "symbol": "VAI",
                "decimals": "18",
                "price": 0.9229,
                "amount": "5052603128894568121505889.46961565436196245506",
                "usdAmount": 4663047.427656797
            },
            "0xb8C540d00dd0Bf76ea12E4B4B95eFC90804f924E": {
                "source": "https://bscscan.com/token/0xb8c540d00dd0bf76ea12e4b4b95efc90804f924e",
                "symbol": "QUSD",
                "decimals": "18",
                "price": 0,
                "amount": "296752558655534627557464",
                "usdAmount": 0
            },
            "0x23396cF899Ca06c4472205fC903bDB4de249D6fC": {
                "source": "https://bscscan.com/tokens",
                "symbol": "UST",
                "decimals": "18",
                "price": 1.0018,
                "amount": "2520890464628290945317636.11740270996633015201",
                "usdAmount": 2525428.0674646217
            },
            "0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c": {
                "source": "https://bscscan.com/tokens",
                "symbol": "BTCB",
                "decimals": "18",
                "price": 57805.1372,
                "amount": "756030957401807997102.34390390134333331495",
                "usdAmount": 43702473.220058866
            },
            "0xfCe146bF3146100cfe5dB4129cf6C82b0eF4Ad8c": {
                "source": "https://bscscan.com/token/0xfce146bf3146100cfe5db4129cf6c82b0ef4ad8c",
                "symbol": "renBTC",
                "decimals": "8",
                "price": 0,
                "amount": "911447490",
                "usdAmount": 0
            },
            "0xeD28A457A5A76596ac48d87C0f577020F6Ea1c4C": {
                "source": "https://bscscan.com/token/0xed28a457a5a76596ac48d87c0f577020f6ea1c4c",
                "symbol": "pBTC",
                "decimals": "18",
                "price": 0,
                "amount": "25007611745216739642.30475122314688704893",
                "usdAmount": 0
            },
            "0x4197C6EF3879a08cD51e5560da5064B773aa1d29": {
                "source": "https://bscscan.com/tokens",
                "symbol": "ACS",
                "decimals": "18",
                "price": 74.1249,
                "amount": "572869577655989293585800.60016428649412060864",
                "usdAmount": 42463900.15679244
            },
            "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c": {
                "source": "https://bscscan.com/tokens",
                "symbol": "WBNB",
                "decimals": "18",
                "price": 626.9016,
                "amount": "106758504039735055559230.73651412958723541124",
                "usdAmount": 66927076.99611637
            },
            "0x2170Ed0880ac9A755fd29B2688956BD959F933F8": {
                "source": "https://bscscan.com/tokens",
                "symbol": "ETH",
                "decimals": "18",
                "price": 2858.2663,
                "amount": "11971817979519835231060.43423832747880188657",
                "usdAmount": 34218643.88059563
            },
            "0x47BEAd2563dCBf3bF2c9407fEa4dC236fAbA485A": {
                "source": "https://bscscan.com/tokens",
                "symbol": "SXP",
                "decimals": "18",
                "price": 5.2483,
                "amount": "11609952769014798591900679.04807305862745330885",
                "usdAmount": 60932515.117620364
            },
            "0xcF6BB5389c92Bdda8a3747Ddb454cB7a64626C63": {
                "source": "https://bscscan.com/tokens",
                "symbol": "XVS",
                "decimals": "18",
                "price": 105.3922,
                "amount": "170545956695585890000134.34066925342435838822",
                "usdAmount": 17974213.577252526
            },
            "0x4338665CBB7B2485A8855A139b75D5e34AB0DB94": {
                "source": "https://bscscan.com/tokens",
                "symbol": "LTC",
                "decimals": "18",
                "price": 272.2279,
                "amount": "29828726565165973076909.13479927669062745148",
                "usdAmount": 8120211.592509346
            },
            "0x7083609fCE4d1d8Dc0C979AAb8c869Ea2C873402": {
                "source": "https://bscscan.com/tokens",
                "symbol": "DOT",
                "decimals": "18",
                "price": 36.7552,
                "amount": "137543489788598056787816.33300912806074887597",
                "usdAmount": 5055438.475877879
            },
            "0xF8A0BF9cF54Bb92F17374d9e9A321E6a111a51bD": {
                "source": "https://bscscan.com/tokens",
                "symbol": "LINK",
                "decimals": "18",
                "price": 38.4612,
                "amount": "188513575673038195010508.58962982776875572331",
                "usdAmount": 7250458.336675856
            },
            "0x3EE2200Efb3400fAbB9AacF31297cBdD1d435D47": {
                "source": "https://bscscan.com/tokens",
                "symbol": "ADA",
                "decimals": "18",
                "price": 1.3517,
                "amount": "9914816891147157947217325.49334640001786762974",
                "usdAmount": 13401857.991763614
            },
            "0x1D2F0da169ceB9fC7B3144628dB156f3F6c60dBE": {
                "source": "https://bscscan.com/tokens",
                "symbol": "XRP",
                "decimals": "18",
                "price": 1.5813,
                "amount": "4423021485829551327298718.24287175163640328809",
                "usdAmount": 6994123.875542269
            },
            "0x250632378E573c6Be1AC2f97Fcdf00515d0Aa91B": {
                "source": "https://bscscan.com/tokens",
                "symbol": "BETH",
                "decimals": "18",
                "price": 1511.7025,
                "amount": "5552229662692764090150.15662039936611162577",
                "usdAmount": 8393319.461666808
            },
            "0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82": {
                "source": "https://bscscan.com/tokens",
                "symbol": "Cake",
                "decimals": "18",
                "price": 40.47,
                "amount": "767600629223921121450400.42308275706397653128",
                "usdAmount": 31064797.464692086
            },
            "0x5b17b4d5e4009B5C43e3e3d63A5229F794cBA389": {
                "source": "https://bscscan.com/token/0x5b17b4d5e4009b5c43e3e3d63a5229f794cba389",
                "symbol": "ACSI",
                "decimals": "18",
                "price": 7.0219,
                "amount": "459339994054725344104161",
                "usdAmount": 3225439.5042528757
            },
            "0x88f1A5ae2A3BF98AEAF342D26B30a79438c9142e": {
                "source": "https://bscscan.com/tokens",
                "symbol": "YFI",
                "decimals": "18",
                "price": 48954.4601,
                "amount": "3232976973709342875.18165658665068542015",
                "usdAmount": 158268.64226367278
            },
            "0xAD6cAEb32CD2c308980a548bD0Bc5AA4306c6c18": {
                "source": "https://bscscan.com/tokens",
                "symbol": "BAND",
                "decimals": "18",
                "price": 17.2316,
                "amount": "6187273904722891237366.66147234623873479767",
                "usdAmount": 106616.62901662297
            },
            "0xb86AbCb37C3A4B64f74f59301AFF131a1BEcC787": {
                "source": "https://bscscan.com/tokens",
                "symbol": "ZIL",
                "decimals": "12",
                "price": 0.21,
                "amount": "430278367677531300.81996886495600623358",
                "usdAmount": 90358.45721228157
            },
            "0x9f589e3eabe42ebC94A44727b3f3531C0c877809": {
                "source": "https://bscscan.com/tokens",
                "symbol": "TKO",
                "decimals": "18",
                "price": 3.34,
                "amount": "114301424507364039560753.6976674748831190559",
                "usdAmount": 381766.7578545959
            },
            "0x2222227E22102Fe3322098e4CBfE18cFebD57c95": {
                "source": "https://bscscan.com/tokens",
                "symbol": "TLM",
                "decimals": "4",
                "price": 0.4498,
                "amount": "2149001222.76280398816712679113",
                "usdAmount": 96662.07499987092
            },
            "0x4B0F1812e5Df2A09796481Ff14017e6005508003": {
                "source": "https://bscscan.com/tokens",
                "symbol": "TWT",
                "decimals": "18",
                "price": 0.6844,
                "amount": "566786412135415713241681.78841572922144759676",
                "usdAmount": 387908.6204654785
            },
            "0x728C5baC3C3e370E372Fc4671f9ef6916b814d8B": {
                "source": "https://bscscan.com/token/0x728c5bac3c3e370e372fc4671f9ef6916b814d8b",
                "symbol": "UNFI",
                "decimals": "18",
                "price": 25.6936,
                "amount": "6793380162054263531032.66666903139106196492",
                "usdAmount": 174546.39253175742
            },
            "0x78650B139471520656b9E7aA7A5e9276814a38e9": {
                "source": "https://bscscan.com/tokens",
                "symbol": "BTCST",
                "decimals": "17",
                "price": 75.18,
                "amount": "386426139153675781252.65217555057692161182",
                "usdAmount": 290515.17141573346
            },
            "0x928e55daB735aa8260AF3cEDadA18B5f70C72f1b": {
                "source": "https://bscscan.com/tokens",
                "symbol": "FRONT",
                "decimals": "18",
                "price": 2.5886,
                "amount": "22445681293080991319347.71329643955173810477",
                "usdAmount": 58102.890595269455
            },
            "0x7A9f28EB62C791422Aa23CeAE1dA9C847cBeC9b0": {
                "source": "https://bscscan.com/token/0x7a9f28eb62c791422aa23ceae1da9c847cbec9b0",
                "symbol": "WATCH",
                "decimals": "18",
                "price": 1.7518,
                "amount": "204814429401059380571888.65826954240791590512",
                "usdAmount": 358793.91742477583
            },
            "0x71DE20e0C4616E7fcBfDD3f875d568492cBE4739": {
                "source": "https://bscscan.com/token/0x71de20e0c4616e7fcbfdd3f875d568492cbe4739",
                "symbol": "SWINGBY",
                "decimals": "18",
                "price": 0,
                "amount": "866623307058855620265547.08973490778000073446",
                "usdAmount": 0
            },
            "0xAC51066d7bEC65Dc4589368da368b212745d63E8": {
                "source": "https://bscscan.com/token/0xac51066d7bec65dc4589368da368b212745d63e8",
                "symbol": "ALICE",
                "decimals": "6",
                "price": 0,
                "amount": "5142093096.55776288455940294944",
                "usdAmount": 0
            },
            "0x658A109C5900BC6d2357c87549B651670E5b0539": {
                "source": "https://bscscan.com/tokens",
                "symbol": "FOR",
                "decimals": "18",
                "price": 0.1155,
                "amount": "329056434919799769229102.82675130940294993091",
                "usdAmount": 38006.01823323687
            },
            "0xa1faa113cbE53436Df28FF0aEe54275c13B40975": {
                "source": "https://bscscan.com/tokens",
                "symbol": "ALPHA",
                "decimals": "18",
                "price": 2.0892,
                "amount": "42723415061318016919578.43322116637197587507",
                "usdAmount": 89257.7587461056
            },
            "0xA8c2B8eec3d368C0253ad3dae65a5F2BBB89c929": {
                "source": "https://bscscan.com/tokens",
                "symbol": "CTK",
                "decimals": "6",
                "price": 2.5223,
                "amount": "13965794090.02645634476264842043",
                "usdAmount": 35225.92243327373
            },
            "0xBf5140A22578168FD562DCcF235E5D43A02ce9B1": {
                "source": "https://bscscan.com/tokens",
                "symbol": "UNI",
                "decimals": "18",
                "price": 40.4683,
                "amount": "8283127133902763752169.26906168316726936995",
                "usdAmount": 335204.0737929172
            },
            "0xD41FDb03Ba84762dD66a0af1a6C8540FF1ba5dfb": {
                "source": "https://bscscan.com/tokens",
                "symbol": "SFP",
                "decimals": "18",
                "price": 2.6975,
                "amount": "99985252922601458005599.05012067944967170782",
                "usdAmount": 269710.21975871746
            },
            "0xECa41281c24451168a37211F0bc2b8645AF45092": {
                "source": "https://bscscan.com/token/0xeca41281c24451168a37211f0bc2b8645af45092",
                "symbol": "TPT",
                "decimals": "4",
                "price": 0.0384,
                "amount": "29086024575.97975290174760776039",
                "usdAmount": 111690.33437176225
            },
            "0x5B6DcF557E2aBE2323c48445E8CC948910d8c2c9": {
                "source": "https://bscscan.com/tokens",
                "symbol": "MIR",
                "decimals": "18",
                "price": 10.1786,
                "amount": "50462568200108533781294.96769475351327291924",
                "usdAmount": 513638.2966816247
            },
            "0x52CE071Bd9b1C4B00A0b92D298c512478CaD67e8": {
                "source": "https://bscscan.com/tokens",
                "symbol": "COMP",
                "decimals": "18",
                "price": 744.0269,
                "amount": "123806039276224451219.85441109566971908027",
                "usdAmount": 92115.02360396752
            },
            "0x947950BcC74888a40Ffa2593C5798F11Fc9124C4": {
                "source": "https://bscscan.com/token/0x947950bcc74888a40ffa2593c5798f11fc9124c4",
                "symbol": "SUSHI",
                "decimals": "18",
                "price": 0,
                "amount": "16965637421050063575379.1862091711608028398",
                "usdAmount": 0
            },
            "0xF21768cCBC73Ea5B6fd3C687208a7c2def2d966e": {
                "source": "https://bscscan.com/tokens",
                "symbol": "REEF",
                "decimals": "18",
                "price": 0.0402,
                "amount": "6748699742910797829371568.68882013097384670457",
                "usdAmount": 271297.7296650141
            }
        }
    }
}
```
